<a id='1'></a>
## 1. 🌟 What is Pandas?

**Pandas** is a Python library used for data manipulation, analysis, and handling structured data using Series and DataFrame objects.

- Built **on top of NumPy**
- Initial release: **2009**
- Core data structures: **Series** (1D) and **DataFrame** (2D)

| Feature | NumPy Array | Pandas DataFrame |
|---------|-------------|------------------|
| Data Types | Homogeneous | Heterogeneous (mixed) |
| Labels | Integer index only | Named rows & columns |
| Missing Data | No built-in support | Built-in NaN handling |
| Best For | Numerical computing | Data analysis & cleaning |

> 💡 **Why ML/DL needs Pandas:**  
> Real datasets come as CSV files with mixed types, string columns, and missing values.  
> Pandas **reads, cleans, and prepares** that data before it enters your model.

<a id='2'></a>
## 2. 📦 Installing & Importing Pandas

In [ ]:
# Install if needed (run once)
# !pip install pandas

In [1]:
# Standard imports — always use these aliases
import pandas as pd
import numpy as np

print("Pandas version :", pd.__version__)
print("NumPy  version :", np.__version__)

Pandas version : 2.3.3
NumPy  version : 2.2.6

<a id='3'></a>
## 3. 📊 Pandas Series

A Pandas **Series** is a **1-dimensional labeled ** data structure that can store data of different types and is similar to a single column in a table.

Every Series has 4 things:
- **Variable name** — the Python variable you store it in
- **Index** — row labels (default: 0, 1, 2, ...)
- **Values** — the actual data
- **Name** — optional label for the Series (becomes column name in a DataFrame)

### 3.1 Creating a Series

In [2]:
# ── From a Python list (default integer index) ──
s1 = pd.Series([10, 20, 30, 40, 50])
print("Series from list:")
print(s1)

Series from list:
0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
s2 = pd.Series(data=["A", "B", "C"], name="C1")
print("Series with name:")
print(s2)

Series with name:
0    A
1    B
2    C
Name: C1, dtype: object

In [8]:
# ── With a custom index ──
s3 = pd.Series([85, 92, 78, 95],
               index=['Ali', 'Sara', 'Ahmed', 'Ayesha'],
               name='Marks')
print("Series with custom index:")
print(s3)

Series with custom index:
Ali       85
Sara      92
Ahmed     78
Ayesha    95
Name: Marks, dtype: int64

In [9]:
# ── From a dictionary (keys → index, values → data) ──
s4 = pd.Series({'Ali': 85, 'Sara': 92, 'Ahmed': 78}, name = "Marks")
print("Series from dictionary:")
print(s4)

Series from dictionary:
Ali      85
Sara     92
Ahmed    78
Name: Marks, dtype: int64

In [10]:
# ── From a NumPy array ──
arr = np.array([5.5, 6.6, 7.7, 8.8])
s5  = pd.Series(arr, name='Values')
print("Series from NumPy array:")
print(s5)

Series from NumPy array:
0    5.5
1    6.6
2    7.7
3    8.8
Name: Values, dtype: float64

### 3.2 Series Attributes:
Series attributes are properties that provide information about a Pandas Series, such as its data type, size, shape, index, and number of elements.

In [11]:
s = pd.Series([85, 92, 78, 95, 88],
              index=['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal'],
              name='Marks')
print(s)
print()
print("── Attributes ──")
print("name     :", s.name)
print("index    :", s.index.tolist())
print("values   :", s.values)
print("dtype    :", s.dtype)
print("shape    :", s.shape)
print("size     :", s.size)

Ali       85
Sara      92
Ahmed     78
Ayesha    95
Bilal     88
Name: Marks, dtype: int64

── Attributes ──
name     : Marks
index    : ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal']
values   : [85 92 78 95 88]
dtype    : int64
shape    : (5,)
size     : 5

### 3.3 Accessing Series Elements:
Accessing Series elements is the process of retrieving individual values or groups of values from a Pandas Series using labels, positions, or conditions.

In [13]:
s = pd.Series([85, 92, 78, 95, 88],
              index=['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal'],
              name='Marks')

# By label
print("s['Ali']           :", s['Ahmed'])

s['Ali']           : 78

In [14]:
# By position
print("s[0]               :", s[0])     # first
print("s[-1]              :", s[-1])    # last

s[0]               : 85
s[-1]              : 88

C:\Users\asadu\AppData\Local\Temp\ipykernel_22448\3655373970.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("s[0]               :", s[0])     # first
C:\Users\asadu\AppData\Local\Temp\ipykernel_22448\3655373970.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("s[-1]              :", s[-1])    # last

In [15]:
# Multiple labels
print("s[['Ali','Ahmed']] :\n", s[['Ali', 'Ahmed']])

# Slice by label (stop is INCLUDED)
print("s['Ali':'Ahmed']   :\n", s['Ali':'Ahmed'])

s[['Ali','Ahmed']] :
 Ali      85
Ahmed    78
Name: Marks, dtype: int64
s['Ali':'Ahmed']   :
 Ali      85
Sara     92
Ahmed    78
Name: Marks, dtype: int64

### 3.4 Series Operations:
Series operations are operations performed on Pandas Series, such as arithmetic calculations, comparisons, filtering, and applying functions to the data.

In [17]:
scores = pd.Series([85, 92, 78, 95, 88], name='Marks')

# Arithmetic — element-wise (just like NumPy)
print("scores + 5  :", (scores + 5).values)

scores + 5  : [ 90  97  83 100  93]

In [19]:
scores = pd.Series([85, 92, 78, 95, 88], name='Marks')

# Arithmetic — element-wise (just like NumPy)
print("scores + 5  :", (scores + 5).values)
print("scores / 100:", (scores / 100).values)
print()

# Boolean comparison
print("scores > 85 :", (scores > 85).values)
print()

# Built-in statistics
print("mean   :", scores.mean())
print("median :", scores.median())
print("std    :", round(scores.std(), 2))
print("min    :", scores.min())
print("max    :", scores.max())

scores + 5  : [ 90  97  83 100  93]
scores / 100: [0.85 0.92 0.78 0.95 0.88]

scores > 85 : [False  True False  True  True]

mean   : 87.6
median : 88.0
std    : 6.58
min    : 78
max    : 95

In [20]:
# value_counts — count occurrences of each unique value
grades = pd.Series(['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B'])
print("Grade counts:")
print(grades.value_counts())

Grade counts:
A    3
B    3
C    2
Name: count, dtype: int64

In [21]:
marks = pd.Series([100, 95, 93, 93, 100, 40, 95])
print("Marks Counts: ")
print(marks.value_counts())

Marks Counts:
100    2
95     2
93     2
40     1
Name: count, dtype: int64

<a id='4'></a>
## 4. 🗃️ Pandas DataFrame:
Pandas **DataFrame** is a **2-dimensional labeled ** data structure that stores data in rows and columns, similar to a table or spreadsheet.

Key points:
- Each **column** is a **Series**
- All columns share the **same index** (row labels)
- Different columns can have **different data types** (heterogeneous)

### 4.1 Creating a DataFrame

In [22]:
# ── Method 1: From a dictionary of lists (most common) ──
# Keys → column names | Values → column data
data = {
    'Name':     ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal'],
    'Age':      [22, 25, 23, 21, 24],
    'Score':    [85, 92, 78, 95, 88],
    'Grade':    ['B', 'A', 'C', 'A', 'B'],
    'City':     ['Lahore', 'Karachi', 'Lahore', 'Islamabad', 'Karachi'],
    'Fee_Paid': [True, True, False, True, False]
}
df = pd.DataFrame(data)
df

     Name  Age  Score Grade       City  Fee_Paid
0     Ali   22     85     B     Lahore      True
1    Sara   25     92     A    Karachi      True
2   Ahmed   23     78     C     Lahore     False
3  Ayesha   21     95     A  Islamabad      True
4   Bilal   24     88     B    Karachi     False

In [24]:
# ── Method 2: From a list of dictionaries ──
# Each dictionary = one row record
records = [
    {'Name': 'Ali',   'Age': 22, 'Score': 85},
    {'Name': 'Sara',  'Age': 25, 'Score': 92},
    {'Name': 'Ahmed', 'Age': 23, 'Score': 78}
]
df2 = pd.DataFrame(records)
print("From list of dicts:")
df2

From list of dicts:

    Name  Age  Score
0    Ali   22     85
1   Sara   25     92
2  Ahmed   23     78

In [26]:
# ── Method 3: From a NumPy array ──
arr = np.array(
    [
        [1, 2, 3], 
        [4, 5, 6], 
        [7, 8, 9]
    ]
)
df3 = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print("From NumPy array:")
df3

From NumPy array:

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [27]:
# ── Method 4: Custom row index ──
df4 = pd.DataFrame({
    'Age':   [22, 25, 23],
    'Score': [85, 92, 78]
}, index=['Ali', 'Sara', 'Ahmed'])   # student names as row labels
print("Custom row index:")
print(df4)

Custom row index:
       Age  Score
Ali     22     85
Sara    25     92
Ahmed   23     78

### 4.2 Every Column is a Series

In [29]:
df = pd.DataFrame({'Name': ['Ali', 'Sara', 'Ahmed'], 'Score': [85, 92, 78]})

# Extract one column → it's a Series!
name_col = df['Name']
print("Type of df['Name']:", type(name_col))
print(name_col)

Type of df['Name']: <class 'pandas.core.series.Series'>
0      Ali
1     Sara
2    Ahmed
Name: Name, dtype: object

In [30]:
# A DataFrame = multiple Series glued together on a shared index
s1 = pd.Series(['Ali', 'Sara', 'Ahmed'], name='Name')
s2 = pd.Series([85, 92, 78],             name='Score')
df_from_series = pd.DataFrame({'Name': s1, 'Score': s2})
print("DataFrame built from two Series:")
print(df_from_series)

DataFrame built from two Series:
    Name  Score
0    Ali     85
1   Sara     92
2  Ahmed     78

<a id='5'></a>
## 5. 🔍 Exploring a DataFrame

**The very first thing you do** when you receive any new dataset — always explore it before touching the data.

In [31]:
# Dataset used for all examples in this section
data = {
    'Name':     ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal', 'Zara', 'Omar', 'Hina'],
    'Age':      [22, 25, 23, 21, 24, 22, 26, 20],
    'Score':    [85, 92, 78, 95, 88, 76, 91, 83],
    'Grade':    ['B', 'A', 'C', 'A', 'B', 'C', 'A', 'B'],
    'City':     ['Lahore', 'Karachi', 'Lahore', 'Islamabad',
                 'Karachi', 'Peshawar', 'Islamabad', 'Peshawar'],
    'Fee_Paid': [True, True, False, True, False, True, True, False]
}
df = pd.DataFrame(data)
df

     Name  Age  Score Grade       City  Fee_Paid
0     Ali   22     85     B     Lahore      True
1    Sara   25     92     A    Karachi      True
2   Ahmed   23     78     C     Lahore     False
3  Ayesha   21     95     A  Islamabad      True
4   Bilal   24     88     B    Karachi     False
5    Zara   22     76     C   Peshawar      True
6    Omar   26     91     A  Islamabad      True
7    Hina   20     83     B   Peshawar     False

In [32]:
# ── shape — (rows, columns) ──
print("Shape   :", df.shape)       # (8, 6)
print("Rows    :", df.shape[0])
print("Columns :", df.shape[1])

Shape   : (8, 6)
Rows    : 8
Columns : 6

In [34]:
# ── head() and tail() ──
print("First 5 rows:")
print(df.head())
print()
print("First 3 rows:")
print(df.head(3))

First 5 rows:
     Name  Age  Score Grade       City  Fee_Paid
0     Ali   22     85     B     Lahore      True
1    Sara   25     92     A    Karachi      True
2   Ahmed   23     78     C     Lahore     False
3  Ayesha   21     95     A  Islamabad      True
4   Bilal   24     88     B    Karachi     False

First 3 rows:
    Name  Age  Score Grade     City  Fee_Paid
0    Ali   22     85     B   Lahore      True
1   Sara   25     92     A  Karachi      True
2  Ahmed   23     78     C   Lahore     False

In [35]:
print("Last 5 rows:")
print(df.tail())
print()
print("Last 2 rows:")
print(df.tail(2))

Last 5 rows:
     Name  Age  Score Grade       City  Fee_Paid
3  Ayesha   21     95     A  Islamabad      True
4   Bilal   24     88     B    Karachi     False
5    Zara   22     76     C   Peshawar      True
6    Omar   26     91     A  Islamabad      True
7    Hina   20     83     B   Peshawar     False

Last 2 rows:
   Name  Age  Score Grade       City  Fee_Paid
6  Omar   26     91     A  Islamabad      True
7  Hina   20     83     B   Peshawar     False

In [38]:
# ── Column names and index ──
print("Columns :", df.columns.tolist())
print("Index   :", df.index.tolist())

Columns : ['Name', 'Age', 'Score', 'Grade', 'City', 'Fee_Paid']
Index   : [0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
# Dataset used for all examples in this section
data = {
    'Name':     ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal', 'Zara', 'Omar', 'Hina'],
    'Age':      [22, 25, 23, 21, 24, 22, 26, 20],
    'Score':    [85, 92, 78, 95, 88, 76, 91, 83],
    'Grade':    ['B', 'A', 'C', 'A', 'B', 'C', 'A', 'B'],
    'City':     ['Lahore', 'Karachi', 'Lahore', 'Islamabad',
                 'Karachi', 'Peshawar', 'Islamabad', 'Peshawar'],
    'Fee_Paid': [True, True, False, True, False, True, True, False]
}
df = pd.DataFrame(data)
df

     Name  Age  Score Grade       City  Fee_Paid
0     Ali   22     85     B         10      True
1    Sara   25     92     A    Karachi      True
2   Ahmed   23     78     C     Lahore     False
3  Ayesha   21     95     A  Islamabad      True
4   Bilal   24     88     B    Karachi     False
5    Zara   22     76     C   Peshawar      True
6    Omar   26     91     A  Islamabad      True
7    Hina   20     83     B   Peshawar     False

In [39]:
# ── dtypes — data type of each column ──
print("Data types:")
print(df.dtypes)

Data types:
Name        object
Age          int64
Score        int64
Grade       object
City        object
Fee_Paid      bool
dtype: object

In [41]:
# ── info() — single most useful first-look command ──
# Shows: column names, non-null count, dtype, memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      8 non-null      object
 1   Age       8 non-null      int64
 2   Score     8 non-null      int64
 3   Grade     8 non-null      object
 4   City      8 non-null      object
 5   Fee_Paid  8 non-null      bool
dtypes: bool(1), int64(2), object(3)
memory usage: 456.0+ bytes

In [42]:
# ── describe() — statistical summary for numerical columns ──
print(df.describe())

            Age      Score
count   8.00000   8.000000
mean   22.87500  86.000000
std     2.03101   6.761234
min    20.00000  76.000000
25%    21.75000  81.750000
50%    22.50000  86.500000
75%    24.25000  91.250000
max    26.00000  95.000000

In [61]:
# ── describe(include='all') — includes string columns too ──
print(df.describe(include='all'))

       Name       Age      Score Grade    City Fee_Paid
count     8   8.00000   8.000000     8       8        8
unique    8       NaN        NaN     3       3        2
top     Ali       NaN        NaN     B  Lahore     True
freq      1       NaN        NaN     3       3        5
mean    NaN  22.87500  86.000000   NaN     NaN      NaN
std     NaN   2.03101   6.761234   NaN     NaN      NaN
min     NaN  20.00000  76.000000   NaN     NaN      NaN
25%     NaN  21.75000  81.750000   NaN     NaN      NaN
50%     NaN  22.50000  86.500000   NaN     NaN      NaN
75%     NaN  24.25000  91.250000   NaN     NaN      NaN
max     NaN  26.00000  95.000000   NaN     NaN      NaN

In [66]:
# ── nunique() — count of unique values per column ──
print("Unique values per column:")
print(df.nunique())

Unique values per column:
Name        8
Age         7
Score       8
Grade       3
City        4
Fee_Paid    2
dtype: int64

In [67]:
# ── unique() — what are the unique values in a column ──
print("Unique grades:", df['Grade'].unique())
print("Unique cities:", df['City'].unique())

Unique grades: ['B' 'A' 'C']
Unique cities: ['Lahore' 'Karachi' 'Islamabad' 'Peshawar']

In [68]:
# ── value_counts() — frequency of each unique value ──
print("Grade distribution:")
print(df['Grade'].value_counts())
print()
print("City distribution:")
print(df['City'].value_counts())

Grade distribution:
Grade
B    3
A    3
C    2
Name: count, dtype: int64

City distribution:
City
Lahore       2
Karachi      2
Islamabad    2
Peshawar     2
Name: count, dtype: int64

<a id='6'></a>
## 6. 🎯 Selecting Data — loc & iloc

loc: Accesses and selects DataFrame rows and columns using labels.

iloc: Accesses and selects DataFrame rows and columns using integer positions.

Two ways to select specific rows and columns:

| | `.iloc` | `.loc` |
|--|---------|--------|
| Full name | **i**nteger **loc**ation | **l**abel **loc**ation |
| Selects by | Integer positions (0, 1, 2…) | Row/column names |
| Slice stop | **Excluded** (like Python) | **Included** |
| Boolean mask | ❌ | ✅ |

> 🧠 **Memory trick:** Think of `.iloc` as "**I** use integers" and `.loc` as "**L**abels"

In [69]:
# Dataset for all selection examples
df = pd.DataFrame({
    'Name':  ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal'],
    'Age':   [22, 25, 23, 21, 24],
    'Score': [85, 92, 78, 95, 88],
    'Grade': ['B', 'A', 'C', 'A', 'B']
})
print(df)

     Name  Age  Score Grade
0     Ali   22     85     B
1    Sara   25     92     A
2   Ahmed   23     78     C
3  Ayesha   21     95     A
4   Bilal   24     88     B

### 6.1 Simple Column Selection (Shortcut — most used)

In [71]:
# Single column → returns a Series
print("Single column → Series:")
print(df['Name'])
print("Type:", type(df['Name']))

Single column → Series:
0       Ali
1      Sara
2     Ahmed
3    Ayesha
4     Bilal
Name: Name, dtype: object
Type: <class 'pandas.core.series.Series'>

In [72]:
# Multiple columns → returns a DataFrame
print("Multiple columns → DataFrame:")
print(df[['Name', 'Score']])
print("Type:", type(df[['Name', 'Score']]))

Multiple columns → DataFrame:
     Name  Score
0     Ali     85
1    Sara     92
2   Ahmed     78
3  Ayesha     95
4   Bilal     88
Type: <class 'pandas.core.frame.DataFrame'>

### 6.2 .iloc — Integer Position Based:
.iloc is a Pandas indexer used to access and select rows and columns from a DataFrame based on their integer positions.

In [73]:
# Single element [row, col] — both by position number
print("Row 0, Col 0      :", df.iloc[0, 0])    # Ali
print("Row 1, Col 2      :", df.iloc[1, 2])    # 92
print("Last row, last col:", df.iloc[-1, -1])  # B

Row 0, Col 0      : Ali
Row 1, Col 2      : 92
Last row, last col: B

In [80]:
# Single full row
print("Row at position 0 (Ali's record):")
print(df.iloc[0])

Row at position 0 (Ali's record):
Name     Ali
Age       22
Score     85
Grade      B
Name: 0, dtype: object

In [77]:
# Single full column by position
print("Column at position 2 (Score):")
print(df.iloc[:, 2])    # : means all rows

Column at position 2 (Score):
0    85
1    92
2    78
3    95
4    88
Name: Score, dtype: int64

In [81]:
# Slice rows — stop is EXCLUDED
print("Rows 1 to 3 (iloc[1:4]):")
print(df.iloc[1:4])    # rows 1, 2, 3 → row 4 NOT included

Rows 1 to 3 (iloc[1:4]):
     Name  Age  Score Grade
1    Sara   25     92     A
2   Ahmed   23     78     C
3  Ayesha   21     95     A

In [82]:
# Select rows by a list of positions
print("Rows 0, 2, 4:")
print(df.iloc[[0, 2, 4]])

Rows 0, 2, 4:
    Name  Age  Score Grade
0    Ali   22     85     B
2  Ahmed   23     78     C
4  Bilal   24     88     B

In [83]:
# Rows AND columns together
print("Rows 0-2, Cols 0-2:")
print(df.iloc[0:3, 0:3])

Rows 0-2, Cols 0-2:
    Name  Age  Score
0    Ali   22     85
1   Sara   25     92
2  Ahmed   23     78

### 6.3 .loc — Label Based:
.loc is a Pandas indexer used to access and select rows and columns from a DataFrame based on their labels.

In [85]:
df = pd.DataFrame({
    'Name':  ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal'],
    'Age':   [22, 25, 23, 21, 24],
    'Score': [85, 92, 78, 95, 88],
    'Grade': ['B', 'A', 'C', 'A', 'B']
})
df

     Name  Age  Score Grade
0     Ali   22     85     B
1    Sara   25     92     A
2   Ahmed   23     78     C
3  Ayesha   21     95     A
4   Bilal   24     88     B

In [84]:
# Single element [row_label, column_name]
print("Row 0, column 'Name'  :", df.loc[0, 'Name'])
print("Row 2, column 'Score' :", df.loc[2, 'Score'])

Row 0, column 'Name'  : Ali
Row 2, column 'Score' : 78

In [86]:
# Single full row by label
print("Row with label 1:")
print(df.loc[1])

Row with label 1:
Name     Sara
Age        25
Score      92
Grade       A
Name: 1, dtype: object

In [87]:
# Single column by name
print("Column 'Score':")
print(df.loc[:, 'Score'])

Column 'Score':
0    85
1    92
2    78
3    95
4    88
Name: Score, dtype: int64

In [88]:
# ⚠️ KEY DIFFERENCE: In .loc the stop IS included!
print("df.loc[1:3] — rows 1, 2, 3 (3 IS included):")
print(df.loc[1:3])
print()
print("df.iloc[1:3] — rows 1, 2 (3 is NOT included):")
print(df.iloc[1:3])

df.loc[1:3] — rows 1, 2, 3 (3 IS included):
     Name  Age  Score Grade
1    Sara   25     92     A
2   Ahmed   23     78     C
3  Ayesha   21     95     A

df.iloc[1:3] — rows 1, 2 (3 is NOT included):
    Name  Age  Score Grade
1   Sara   25     92     A
2  Ahmed   23     78     C

In [89]:
# Select specific columns by name list
print("Name and Score columns:")
print(df.loc[:, ['Name', 'Score']])

Name and Score columns:
     Name  Score
0     Ali     85
1    Sara     92
2   Ahmed     78
3  Ayesha     95
4   Bilal     88

In [90]:
# Slice columns by name — stop IS included
print("Columns from Name to Score:")
print(df.loc[:, 'Name':'Score'])    # Name, Age, Score (all three)

Columns from Name to Score:
     Name  Age  Score
0     Ali   22     85
1    Sara   25     92
2   Ahmed   23     78
3  Ayesha   21     95
4   Bilal   24     88

In [91]:
# With a string-based row index (custom labels)
df_custom = pd.DataFrame({
    'Age':   [22, 25, 23],
    'Score': [85, 92, 78]
}, index=['Ali', 'Sara', 'Ahmed'])

print(df_custom)

       Age  Score
Ali     22     85
Sara    25     92
Ahmed   23     78

In [99]:
print("df_custom.loc['Sara']        :", df_custom.loc['Sara'].to_dict())
print("df_custom.loc['Sara','Score']:", df_custom.loc['Sara', 'Score'])

df_custom.loc['Sara']        : {'Age': 25, 'Score': 92}
df_custom.loc['Sara','Score']: 92

<a id='7'></a>
## 7. 🔎 Filtering Data
Filtering data is the process of selecting only the rows or values that meet a specific condition.

OR:

Filtering means **selecting rows that meet a condition** — like a SQL WHERE clause.

In [100]:
# Dataset for filtering examples
df = pd.DataFrame({
    'Name':  ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal', 'Zara'],
    'Age':   [22, 25, 23, 21, 24, 22],
    'Score': [85, 92, 78, 95, 88, 76],
    'Grade': ['B', 'A', 'C', 'A', 'B', 'C'],
    'City':  ['Lahore', 'Karachi', 'Lahore', 'Islamabad', 'Peshawar', 'Lahore']
})
print(df)

     Name  Age  Score Grade       City
0     Ali   22     85     B     Lahore
1    Sara   25     92     A    Karachi
2   Ahmed   23     78     C     Lahore
3  Ayesha   21     95     A  Islamabad
4   Bilal   24     88     B   Peshawar
5    Zara   22     76     C     Lahore

In [102]:
# ── Single condition ──
print("Students with Score > 85:")
print(df[df['Score'] > 85])

Students with Score > 85:
     Name  Age  Score Grade       City
1    Sara   25     92     A    Karachi
3  Ayesha   21     95     A  Islamabad
4   Bilal   24     88     B   Peshawar

In [103]:
print("Students from Lahore:")
print(df[df['City'] == 'Lahore'])

Students from Lahore:
    Name  Age  Score Grade    City
0    Ali   22     85     B  Lahore
2  Ahmed   23     78     C  Lahore
5   Zara   22     76     C  Lahore

In [104]:
# ── AND condition (&) — BOTH must be True ──
print("Score > 80 AND City is Lahore:")
print(df[(df['Score'] > 80) & (df['City'] == 'Lahore')])

Score > 80 AND City is Lahore:
  Name  Age  Score Grade    City
0  Ali   22     85     B  Lahore

In [109]:
# ── OR condition (|) — at least one must be True ──
print("Grade A OR Score > 90:")
print(df[(df['Grade'] == 'A') | (df['Score'] > 90)])

Grade A OR Score > 90:
     Name  Age  Score Grade       City
1    Sara   25     92     A    Karachi
3  Ayesha   21     95     A  Islamabad

In [112]:
# ── NOT condition (~) — negate ──
print("Students NOT from Lahore:")
print(df[~(df['City'] == 'Lahore')])

Students NOT from Lahore:
     Name  Age  Score Grade       City
1    Sara   25     92     A    Karachi
3  Ayesha   21     95     A  Islamabad
4   Bilal   24     88     B   Peshawar

In [113]:
# ── isin() — check if value is in a list ──
print("Students from Lahore or Karachi:")
print(df[df['City'].isin(['Lahore', 'Karachi'])])

Students from Lahore or Karachi:
    Name  Age  Score Grade     City
0    Ali   22     85     B   Lahore
1   Sara   25     92     A  Karachi
2  Ahmed   23     78     C   Lahore
5   Zara   22     76     C   Lahore

In [114]:
# ── between() — range check (both ends included) ──
print("Students with Score between 80 and 92:")
print(df[df['Score'].between(80, 92)])

Students with Score between 80 and 92:
    Name  Age  Score Grade      City
0    Ali   22     85     B    Lahore
1   Sara   25     92     A   Karachi
4  Bilal   24     88     B  Peshawar

In [115]:
# ── Filter rows + select specific columns ──
print("Name and Score of Grade A students only:")
print(df.loc[df['Grade'] == 'A', ['Name', 'Score']])

Name and Score of Grade A students only:
     Name  Score
1    Sara     92
3  Ayesha     95

<a id='8'></a>
## 8. ➕ Adding & Removing Columns

In [116]:
df = pd.DataFrame({
    'Name':  ['Ali', 'Sara', 'Ahmed', 'Ayesha'],
    'Score': [85, 92, 78, 95],
    'Age':   [22, 25, 23, 21]
})
print("Original:")
print(df)

Original:
     Name  Score  Age
0     Ali     85   22
1    Sara     92   25
2   Ahmed     78   23
3  Ayesha     95   21

In [117]:
# ── Add new columns ──
df['Percentage'] = df['Score'] / 100               # derived from existing column
df['Pass']       = df['Score'] >= 80               # boolean column

print("After adding new columns:")
print(df)

After adding new columns:
     Name  Score  Age  Percentage   Pass
0     Ali     85   22        0.85   True
1    Sara     92   25        0.92   True
2   Ahmed     78   23        0.78  False
3  Ayesha     95   21        0.95   True

In [118]:
# ── Add column with apply() + lambda ──
df['Grade'] = df['Score'].apply(lambda x: 'A' if x >= 90
                                     else 'B' if x >= 80
                                     else 'C')
print("With Grade column:")
print(df[['Name', 'Score', 'Grade']])

With Grade column:
     Name  Score Grade
0     Ali     85     B
1    Sara     92     A
2   Ahmed     78     C
3  Ayesha     95     A

In [119]:
# ── Modify an existing column ──
df['Score'] = df['Score'] + 2    # add 2 bonus marks
print("After +2 bonus:")
print(df[['Name', 'Score']])

After +2 bonus:
     Name  Score
0     Ali     87
1    Sara     94
2   Ahmed     80
3  Ayesha     97

In [120]:
# ── Rename columns ──
df_renamed = df.rename(columns={'Name': 'StudentName', 'Score': 'Marks'})
print("Renamed columns:", df_renamed.columns.tolist())

Renamed columns: ['StudentName', 'Marks', 'Age', 'Percentage', 'Pass', 'Grade']

In [121]:
# ── Remove columns ──
df_dropped = df.drop(columns=['Percentage', 'Pass'])
print("After dropping columns:")
print(df_dropped)

After dropping columns:
     Name  Score  Age Grade
0     Ali     87   22     B
1    Sara     94   25     A
2   Ahmed     80   23     C
3  Ayesha     97   21     A

In [ ]:
# ── Remove rows ──
df_row_dropped = df.drop(index=[0, 2])   # drop rows at index 0 and 2
print("After dropping rows 0 and 2:")
print(df_row_dropped)

After dropping rows 0 and 2:
     Name  Score  Age  Percentage  Pass Grade
1    Sara     94   25        0.92  True     A
3  Ayesha     97   21        0.95  True     A

After reset_index:
     Name  Score  Age  Percentage  Pass Grade
0    Sara     94   25        0.92  True     A
1  Ayesha     97   21        0.95  True     A

In [123]:
# Reset index after dropping rows
df_reset = df_row_dropped.reset_index(drop=True)
print("\nAfter reset_index:")
print(df_reset)

After reset_index:
     Name  Score  Age  Percentage  Pass Grade
0    Sara     94   25        0.92  True     A
1  Ayesha     97   21        0.95  True     A

<a id='9'></a>
## 9. ⚙️ Basic DataFrame Operations
DataFrame operations are actions performed on rows and columns to manipulate, analyze, transform, and summarize tabular data, sorting, duplicates, type conversion, apply, map, and groupby.

In [124]:
# Dataset for this section
df = pd.DataFrame({
    'Name':  ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal', 'Zara', 'Omar'],
    'Age':   [22, 25, 23, 21, 24, 22, 23],
    'Score': [85, 92, 78, 95, 88, 76, 92],
    'Grade': ['B', 'A', 'C', 'A', 'B', 'C', 'A'],
    'City':  ['Lahore', 'Karachi', 'Lahore', 'Islamabad',
               'Karachi', 'Lahore', 'Islamabad']
})
print(df)

     Name  Age  Score Grade       City
0     Ali   22     85     B     Lahore
1    Sara   25     92     A    Karachi
2   Ahmed   23     78     C     Lahore
3  Ayesha   21     95     A  Islamabad
4   Bilal   24     88     B    Karachi
5    Zara   22     76     C     Lahore
6    Omar   23     92     A  Islamabad

### 9.1 Sorting:
Sorting is the process of arranging DataFrame rows based on the values of one or more columns in ascending or descending order.

In [125]:
# Sort by one column
print("Ascending by Score:")
print(df.sort_values('Score'))
print()
print("Descending by Score:")
print(df.sort_values('Score', ascending=False))

Ascending by Score:
     Name  Age  Score Grade       City
5    Zara   22     76     C     Lahore
2   Ahmed   23     78     C     Lahore
0     Ali   22     85     B     Lahore
4   Bilal   24     88     B    Karachi
6    Omar   23     92     A  Islamabad
1    Sara   25     92     A    Karachi
3  Ayesha   21     95     A  Islamabad

Descending by Score:
     Name  Age  Score Grade       City
3  Ayesha   21     95     A  Islamabad
6    Omar   23     92     A  Islamabad
1    Sara   25     92     A    Karachi
4   Bilal   24     88     B    Karachi
0     Ali   22     85     B     Lahore
2   Ahmed   23     78     C     Lahore
5    Zara   22     76     C     Lahore

In [129]:
# Sort by multiple columns
print("Sort by City (asc), then Score (desc):")
print(df.sort_values(['City', 'Score'], ascending=[True, False]))

Sort by City (asc), then Score (desc):
     Name  Age  Score Grade       City
3  Ayesha   21     95     A  Islamabad
6    Omar   23     92     A  Islamabad
1    Sara   25     92     A    Karachi
4   Bilal   24     88     B    Karachi
0     Ali   22     85     B     Lahore
2   Ahmed   23     78     C     Lahore
5    Zara   22     76     C     Lahore

### 9.2 Duplicates:
Duplicates are repeated rows or values in a DataFrame that contain the same data or identical information.

In [130]:
df_dups = pd.DataFrame({
    'Name':  ['Ali', 'Sara', 'Ali', 'Ahmed', 'Sara'],
    'Score': [85, 92, 85, 78, 92]
})
print("Data with duplicates:")
print(df_dups)

Data with duplicates:
    Name  Score
0    Ali     85
1   Sara     92
2    Ali     85
3  Ahmed     78
4   Sara     92

In [131]:
print("Duplicate mask (True = duplicate):")
print(df_dups.duplicated())
print("Total duplicates:", df_dups.duplicated().sum())

Duplicate mask (True = duplicate):
0    False
1    False
2     True
3    False
4     True
dtype: bool
Total duplicates: 2

In [132]:
# Show the actual duplicate rows
print("The duplicate rows:")
print(df_dups[df_dups.duplicated()])

The duplicate rows:
   Name  Score
2   Ali     85
4  Sara     92

In [133]:
# Remove duplicates (keeps first occurrence by default)
df_clean = df_dups.drop_duplicates()
print("After drop_duplicates():")
print(df_clean)

# Keep last occurrence
df_last = df_dups.drop_duplicates(keep='last')
print("\nKeep last:")
print(df_last)

After drop_duplicates():
    Name  Score
0    Ali     85
1   Sara     92
3  Ahmed     78

Keep last:
    Name  Score
2    Ali     85
3  Ahmed     78
4   Sara     92

### 9.3 Data Type Conversion:
Data Type Conversion is the process of changing data from one data type to another, such as converting strings to integers, floats, or dates.

In [134]:
# Common real-world problem: columns loaded as wrong type
df_raw = pd.DataFrame({
    'Name':   ['Ali', 'Sara', 'Ahmed'],
    'Age':    ['22', '25', '23'],    # loaded as string from CSV!
    'Score':  [85.0, 92.0, 78.0],
    'Passed': [1, 1, 0]              # int, should be bool
})
print("Original dtypes:")
print(df_raw.dtypes)

Original dtypes:
Name       object
Age        object
Score     float64
Passed      int64
dtype: object

In [135]:
# Convert types using astype()
df_raw['Age']    = df_raw['Age'].astype(int)
df_raw['Score']  = df_raw['Score'].astype(int)
df_raw['Passed'] = df_raw['Passed'].astype(bool)

print("After type conversion:")
print(df_raw.dtypes)
print()
print(df_raw)

After type conversion:
Name      object
Age        int64
Score      int64
Passed      bool
dtype: object

    Name  Age  Score  Passed
0    Ali   22     85    True
1   Sara   25     92    True
2  Ahmed   23     78   False

### 9.4 apply() — Applying Functions to Columns:
apply() is a Pandas method used to apply a function to each value or along an axis of a DataFrame or Series.

In [138]:
df = pd.DataFrame({
    'Name':  ['ali khan', 'SARA AHMED', 'ahmed bilal'],
    'Score': [85, 92, 78]
})

# apply with lambda — simple one-liners
df['Status']      = df['Score'].apply(lambda x: 'Pass' if x >= 80 else 'Fail')
df['Name_Clean']  = df['Name'].apply(lambda x: x.strip().title())
print(df)

          Name  Score Status   Name_Clean
0     ali khan     85   Pass     Ali Khan
1   SARA AHMED     92   Pass   Sara Ahmed
2  ahmed bilal     78   Fail  Ahmed Bilal

In [139]:
# apply with a full function — for complex logic
def assign_grade(score):
    if   score >= 90: return 'A'
    elif score >= 80: return 'B'
    elif score >= 70: return 'C'
    else:             return 'F'

df['Grade'] = df['Score'].apply(assign_grade)
print(df[['Name_Clean', 'Score', 'Grade']])

    Name_Clean  Score Grade
0     Ali Khan     85     B
1   Sara Ahmed     92     A
2  Ahmed Bilal     78     C

### 9.5 map() — Replacing Values:
map() is a Pandas method used to transform or replace values in a Series by mapping each value to a new value.

In [141]:
df = pd.DataFrame({
    'Name':  ['Ali', 'Sara', 'Ahmed', 'Ayesha'],
    'Grade': ['A', 'B', 'C', 'A'],
    'City':  ['Lahore', 'Karachi', 'Lahore', 'Islamabad']
})

# map with a dictionary — replace each value
grade_to_gpa = {'A': 4.0, 'B': 3.0, 'C': 2.0}
city_to_code = {'Lahore': 'LHR', 'Karachi': 'KHI', 'Islamabad': 'ISB'}

df['GPA']       = df['Grade'].map(grade_to_gpa)
df['City_Code'] = df['City'].map(city_to_code)

print(df)

     Name Grade       City  GPA City_Code
0     Ali     A     Lahore  4.0       LHR
1    Sara     B    Karachi  3.0       KHI
2   Ahmed     C     Lahore  2.0       LHR
3  Ayesha     A  Islamabad  4.0       ISB

### 9.6 groupby() — Group & Aggregate:
groupby() is a Pandas method used to group data based on one or more columns and apply aggregate functions to summarize each group.

In [146]:
df = pd.DataFrame({
    'Name':  ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal', 'Zara'],
    'City':  ['Lahore', 'Karachi', 'Lahore', 'Islamabad', 'Karachi', 'Lahore'],
    'Score': [85, 92, 78, 95, 88, 76],
    'Age':   [22, 25, 23, 21, 24, 22]
})

# Average score per city
print("Average score per city:")
print(df.groupby('City')['Score'].mean())

Average score per city:
City
Islamabad    95.000000
Karachi      90.000000
Lahore       79.666667
Name: Score, dtype: float64

In [147]:
# Multiple statistics at once with agg()
print("Score stats per city:")
print(df.groupby('City')['Score'].agg(['mean', 'max', 'min', 'count']))

Score stats per city:
                mean  max  min  count
City
Islamabad  95.000000   95   95      1
Karachi    90.000000   92   88      2
Lahore     79.666667   85   76      3

In [ ]:
# Aggregate multiple columns
print("Score and Age per city:")
print(df.groupby('City').agg({'Score': 'mean', 'Age': 'mean'}).round(1))

<a id='10'></a>
## 10. 🩹 Handling Missing Data:
Handling missing data is the process of identifying and managing missing values in a dataset by removing them, replacing them, or using appropriate methods to handle them.

OR:

Missing values appear as **NaN** (Not a Number) in Pandas — inherited from NumPy.

**Two main strategies:**
```
Missing Value Treatment
├── DELETIONS
│   ├── Drop rows (listwise)
│   └── Drop columns
└── IMPUTATIONS (filling)
    ├── For Non-Time-Series → Constant / Mean / Median / Mode
    └── For Time-Series     → Forward Fill / Backward Fill / Interpolation
```

In [148]:
# Dataset with missing values
data = {
    'Name':   ['Ali',    'Sara',   'Ahmed',   'Ayesha',     'Bilal',  'Zara'],
    'Age':    [22.0,      25.0,    np.nan,     21.0,         np.nan,   24.0],
    'Score':  [85.0,     np.nan,   78.0,       95.0,         88.0,    np.nan],
    'City':   ['Lahore', np.nan,   'Karachi',  'Islamabad',  'Lahore', np.nan],
    'Grade':  ['B',      'A',      'C',        'A',          np.nan,   'C']
}
df = pd.DataFrame(data)
print("Dataset with missing values:")
print(df)

Dataset with missing values:
     Name   Age  Score       City Grade
0     Ali  22.0   85.0     Lahore     B
1    Sara  25.0    NaN        NaN     A
2   Ahmed   NaN   78.0    Karachi     C
3  Ayesha  21.0   95.0  Islamabad     A
4   Bilal   NaN   88.0     Lahore   NaN
5    Zara  24.0    NaN        NaN     C

### 10.1 Detecting Missing Values:
Detecting missing values is the process of identifying empty, null, or unavailable data values in a dataset.

In [149]:
# isnull() — True where NaN
print("isnull() map:")
print(df.isnull())

isnull() map:
    Name    Age  Score   City  Grade
0  False  False  False  False  False
1  False  False   True   True  False
2  False   True  False  False  False
3  False  False  False  False  False
4  False   True  False  False   True
5  False  False   True   True  False

In [150]:
# Count missing per column
print("Missing count per column:")
print(df.isnull().sum())
print()
print("Missing percentage per column:")
print((df.isnull().sum() / len(df) * 100).round(1))

Missing count per column:
Name     0
Age      2
Score    2
City     2
Grade    1
dtype: int64

Missing percentage per column:
Name      0.0
Age      33.3
Score    33.3
City     33.3
Grade    16.7
dtype: float64

In [151]:
# Total missing in the whole DataFrame
print("Total NaN:", df.isnull().sum().sum())

# Rows that have AT LEAST one missing value
print("\nRows with any missing:")
print(df[df.isnull().any(axis=1)])

# Rows that are complete (no missing at all)
print("\nComplete rows:")
print(df[df.notnull().all(axis=1)])

Total NaN: 7

Rows with any missing:
    Name   Age  Score     City Grade
1   Sara  25.0    NaN      NaN     A
2  Ahmed   NaN   78.0  Karachi     C
4  Bilal   NaN   88.0   Lahore   NaN
5   Zara  24.0    NaN      NaN     C

Complete rows:
     Name   Age  Score       City Grade
0     Ali  22.0   85.0     Lahore     B
3  Ayesha  21.0   95.0  Islamabad     A

### 10.2 Deletion Strategies:
Deletion strategies are methods used to remove missing values, unnecessary rows, columns, or duplicate data from a dataset.

In [152]:
# Drop rows with ANY NaN (listwise deletion)
df_dropped = df.dropna()
print("dropna() — drop rows with any NaN:")
print(df_dropped)
print(f"\nShape: {df.shape} → {df_dropped.shape}")

dropna() — drop rows with any NaN:
     Name   Age  Score       City Grade
0     Ali  22.0   85.0     Lahore     B
3  Ayesha  21.0   95.0  Islamabad     A

Shape: (6, 5) → (2, 5)

In [153]:
# Drop rows where specific columns are NaN
df_sub = df.dropna(subset=['Age', 'Score'])
print("Drop only where Age or Score is NaN:")
print(df_sub)

Drop only where Age or Score is NaN:
     Name   Age  Score       City Grade
0     Ali  22.0   85.0     Lahore     B
3  Ayesha  21.0   95.0  Islamabad     A

In [154]:
# Drop COLUMNS that have any NaN
df_col = df.dropna(axis=1)
print("Drop columns with any NaN:")
print(df_col)

Drop columns with any NaN:
     Name
0     Ali
1    Sara
2   Ahmed
3  Ayesha
4   Bilal
5    Zara

### 10.3 Imputation — Filling Missing Values:
Imputation is the process of replacing missing values in a dataset with estimated or appropriate values.

In [155]:
# ── Fill with a constant ──
df_const = df.copy()
df_const['Age']   = df_const['Age'].fillna(0)
df_const['City']  = df_const['City'].fillna('Unknown')
df_const['Grade'] = df_const['Grade'].fillna('Unknown')
print("Fill with constant:")
print(df_const)

Fill with constant:
     Name   Age  Score       City    Grade
0     Ali  22.0   85.0     Lahore        B
1    Sara  25.0    NaN    Unknown        A
2   Ahmed   0.0   78.0    Karachi        C
3  Ayesha  21.0   95.0  Islamabad        A
4   Bilal   0.0   88.0     Lahore  Unknown
5    Zara  24.0    NaN    Unknown        C

In [156]:
# ── Fill with MEAN (for numerical — no outliers) ──
df_mean = df.copy()
df_mean['Age']   = df_mean['Age'].fillna(df_mean['Age'].mean())
df_mean['Score'] = df_mean['Score'].fillna(df_mean['Score'].mean())

print(f"Age mean   = {df['Age'].mean():.2f}")
print(f"Score mean = {df['Score'].mean():.2f}")
print()
print("After mean fill:")
print(df_mean)

Age mean   = 23.00
Score mean = 86.50

After mean fill:
     Name   Age  Score       City Grade
0     Ali  22.0   85.0     Lahore     B
1    Sara  25.0   86.5        NaN     A
2   Ahmed  23.0   78.0    Karachi     C
3  Ayesha  21.0   95.0  Islamabad     A
4   Bilal  23.0   88.0     Lahore   NaN
5    Zara  24.0   86.5        NaN     C

In [158]:
# ── Fill with MEDIAN (for numerical — with outliers) ──
df_median = df.copy()
df_median['Age']   = df_median['Age'].fillna(df_median['Age'].median())
df_median['Score'] = df_median['Score'].fillna(df_median['Score'].median())

print(f"Age median   = {df['Age'].median()}")
print(f"Score median = {df['Score'].median()}")
print()
print("After median fill:")
print(df_median)

Age median   = 23.0
Score median = 86.5

After median fill:
     Name   Age  Score       City Grade
0     Ali  22.0   85.0     Lahore     B
1    Sara  25.0   86.5        NaN     A
2   Ahmed  23.0   78.0    Karachi     C
3  Ayesha  21.0   95.0  Islamabad     A
4   Bilal  23.0   88.0     Lahore   NaN
5    Zara  24.0   86.5        NaN     C

In [159]:
# ── Fill with MODE (for categorical columns) ──
df_mode = df.copy()
# mode() returns a Series, so take [0] to get the value
df_mode['City']  = df_mode['City'].fillna(df_mode['City'].mode()[0])
df_mode['Grade'] = df_mode['Grade'].fillna(df_mode['Grade'].mode()[0])

print(f"City mode  = {df['City'].mode()[0]}")
print(f"Grade mode = {df['Grade'].mode()[0]}")
print()
print("After mode fill:")
print(df_mode)

City mode  = Lahore
Grade mode = A

After mode fill:
     Name   Age  Score       City Grade
0     Ali  22.0   85.0     Lahore     B
1    Sara  25.0    NaN     Lahore     A
2   Ahmed   NaN   78.0    Karachi     C
3  Ayesha  21.0   95.0  Islamabad     A
4   Bilal   NaN   88.0     Lahore     A
5    Zara  24.0    NaN     Lahore     C

### 10.4 Time-Series Imputation — ffill, bfill, interpolate:
Time-Series Imputation is the process of filling missing values in time-ordered data using nearby values.

**ffill (Forward Fill):** Fills a missing value with the previous available value.

**bfill (Backward Fill):** Fills a missing value with the next available value.

**interpolate:** Estimates missing values based on the values before and after the missing value.

In [164]:
# Simulated time-series with missing gaps
ts = pd.Series(
    [10.0, np.nan, np.nan, 40.0, 50.0, np.nan, 70.0],
    index=pd.date_range('2024-01-01', periods=7, freq='D')
)
print("Original time series:")
print(ts)

Original time series:
2024-01-01    10.0
2024-01-02     NaN
2024-01-03     NaN
2024-01-04    40.0
2024-01-05    50.0
2024-01-06     NaN
2024-01-07    70.0
Freq: D, dtype: float64

In [165]:
# Forward Fill — carry LAST known value forward
print("Forward Fill (ffill):")
print(ts.ffill())

Forward Fill (ffill):
2024-01-01    10.0
2024-01-02    10.0
2024-01-03    10.0
2024-01-04    40.0
2024-01-05    50.0
2024-01-06    50.0
2024-01-07    70.0
Freq: D, dtype: float64

In [166]:
# Backward Fill — use NEXT known value to fill backward
print("Backward Fill (bfill):")
print(ts.bfill())

Backward Fill (bfill):
2024-01-01    10.0
2024-01-02    40.0
2024-01-03    40.0
2024-01-04    40.0
2024-01-05    50.0
2024-01-06    70.0
2024-01-07    70.0
Freq: D, dtype: float64

In [170]:
# Linear Interpolation — estimate values between known points
print("Linear Interpolation:")
print(ts.interpolate(method='linear'))

Linear Interpolation:
2024-01-01    10.0
2024-01-02    20.0
2024-01-03    30.0
2024-01-04    40.0
2024-01-05    50.0
2024-01-06    60.0
2024-01-07    70.0
Freq: D, dtype: float64

In [168]:
# Side-by-side comparison of all three
comparison = pd.DataFrame({
    'Original':     ts.values,
    'ffill':        ts.ffill().values,
    'bfill':        ts.bfill().values,
    'interpolated': ts.interpolate().values
}, index=ts.index)
print("All methods compared:")
print(comparison)

All methods compared:
            Original  ffill  bfill  interpolated
2024-01-01      10.0   10.0   10.0          10.0
2024-01-02       NaN   10.0   40.0          20.0
2024-01-03       NaN   10.0   40.0          30.0
2024-01-04      40.0   40.0   40.0          40.0
2024-01-05      50.0   50.0   50.0          50.0
2024-01-06       NaN   50.0   70.0          60.0
2024-01-07      70.0   70.0   70.0          70.0

### 10.5 When to Use Which Strategy?

| Strategy | Best When |
|----------|-----------|
| Drop rows | Missing < 5% and random |
| Drop column | Column > 50% missing |
| Fill constant | Categorical or 0 is meaningful |
| Fill mean | Numeric, no outliers |
| Fill median | Numeric, outliers present |
| Fill mode | Categorical columns |
| Forward fill | Time-series (use last measurement) |
| Backward fill | Time-series (use next measurement) |
| Interpolation | Time-series with gradual changes |

### 10.6 Complete Cleaning Pipeline:
A Complete Cleaning Pipeline is a sequence of steps used to prepare raw data for analysis or machine learning by handling missing values, duplicates, incorrect data types, outliers, and other data quality issues.

In [171]:
# Messy raw dataset
raw = pd.DataFrame({
    'Name':   ['Ali',     'Sara',   'Ali',    'Ahmed',  'Ayesha',    np.nan],
    'Age':    [22,         25,       22,       np.nan,   21,          24],
    'Score':  [85,        np.nan,   85,        78,       95,          88],
    'City':   ['Lahore',  'Karachi', 'Lahore', 'Lahore', np.nan,      'Islamabad'],
    'Grade':  ['B',       'A',      'B',       'C',      'A',         np.nan]
})

print("=== RAW DATA ===")
print(raw)
print(f"Missing values: {raw.isnull().sum().sum()}")
print(f"Duplicates: {raw.duplicated().sum()}")
print()

=== RAW DATA ===
     Name   Age  Score       City Grade
0     Ali  22.0   85.0     Lahore     B
1    Sara  25.0    NaN    Karachi     A
2     Ali  22.0   85.0     Lahore     B
3   Ahmed   NaN   78.0     Lahore     C
4  Ayesha  21.0   95.0        NaN     A
5     NaN  24.0   88.0  Islamabad   NaN
Missing values: 5
Duplicates: 1

In [172]:
# ── Step 1: Drop rows with no Name ──
clean = raw.dropna(subset=['Name'])
print(f"Step 1 — Drop unnamed rows : {raw.shape} → {clean.shape}")

Step 1 — Drop unnamed rows : (6, 5) → (5, 5)

In [173]:
# ── Step 2: Remove duplicate rows ──
clean = clean.drop_duplicates()
print(f"Step 2 — Remove duplicates  : → {clean.shape}")

Step 2 — Remove duplicates  : → (4, 5)

In [174]:

# ── Step 3: Fill numerical with median ──
clean['Age']   = clean['Age'].fillna(clean['Age'].median())
clean['Score'] = clean['Score'].fillna(clean['Score'].median())
print("Step 3 — Fill Age/Score with median")

Step 3 — Fill Age/Score with median

In [175]:
# ── Step 4: Fill categorical with mode ──
clean['City']  = clean['City'].fillna(clean['City'].mode()[0])
clean['Grade'] = clean['Grade'].fillna(clean['Grade'].mode()[0])
print("Step 4 — Fill City/Grade with mode")

Step 4 — Fill City/Grade with mode

In [176]:

# ── Step 5: Reset index ──
clean = clean.reset_index(drop=True)
print("Step 5 — Reset index")

Step 5 — Reset index

In [177]:

print()
print("=== CLEANED DATA ===")
print(clean)
print(f"\nMissing values remaining: {clean.isnull().sum().sum()}")

=== CLEANED DATA ===
     Name   Age  Score     City Grade
0     Ali  22.0   85.0   Lahore     B
1    Sara  25.0   85.0  Karachi     A
2   Ahmed  22.0   78.0   Lahore     C
3  Ayesha  21.0   95.0   Lahore     A

Missing values remaining: 0

---

## 🎯 Quick Reference Cheatsheet

| Category | Method | Purpose |
|----------|--------|---------|
| **Create** | `pd.Series(data, index, name)` | 1D labeled array |
| | `pd.DataFrame(dict)` | 2D labeled table |
| **Explore** | `df.head(n)` / `df.tail(n)` | Preview rows |
| | `df.shape` | (rows, cols) |
| | `df.info()` | Types + non-null counts |
| | `df.describe()` | Statistical summary |
| | `df.dtypes` | Column data types |
| | `df.nunique()` | Unique count per col |
| | `df['col'].value_counts()` | Frequency of values |
| **Select** | `df['col']` | Single column (Series) |
| | `df[['c1','c2']]` | Multiple columns (DF) |
| | `df.iloc[r, c]` | By integer position |
| | `df.loc[r, c]` | By label |
| **Filter** | `df[df['col'] > val]` | Boolean condition |
| | `df['col'].isin([...])` | Membership check |
| | `df['col'].between(a, b)` | Range check |
| **Modify** | `df['new_col'] = values` | Add column |
| | `df.drop(columns=[...])` | Remove columns |
| | `df.rename(columns={})` | Rename columns |
| | `df['col'].apply(fn)` | Apply function |
| | `df['col'].map({})` | Replace values |
| **Sort** | `df.sort_values('col')` | Sort rows |
| **Dups** | `df.duplicated()` | Find duplicates |
| | `df.drop_duplicates()` | Remove duplicates |
| **Missing** | `df.isnull().sum()` | Count NaN per col |
| | `df.dropna()` | Drop NaN rows |
| | `df.fillna(val)` | Fill NaN with value |
| | `df['col'].ffill()` | Forward fill |
| | `df['col'].bfill()` | Backward fill |
| | `df['col'].interpolate()` | Linear interpolation |
| **Group** | `df.groupby('col').agg()` | Group & aggregate |

---

## 🏁 What We Covered

✅ **What Pandas is** — how it differs from NumPy  
✅ **Series** — creation, attributes, indexing, operations  
✅ **DataFrame** — creation from dicts, lists, NumPy arrays  
✅ **Exploring** — head, tail, info, describe, dtypes, value_counts  
✅ **loc vs iloc** — label-based vs integer-position selection  
✅ **Filtering** — single/multiple conditions, isin, between  
✅ **Adding/Removing** — columns, rows, rename, reset_index  
✅ **Operations** — sort, duplicates, type conversion, apply, map, groupby  
✅ **Missing Data** — detect, drop, fill (mean/median/mode/ffill/bfill/interpolate)